/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConvertConvertRouteImport } from './routes/_convert/convert'
import { Route as ConvertConvertIndexRouteImport } from './routes/_convert/convert.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertConvertRoute = ConvertConvertRouteImport.update({
  id: '/_convert/convert',
  path: '/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertConvertIndexRoute = ConvertConvertIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConvertConvertRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/convert': typeof ConvertConvertRouteWithChildren
  '/convert/': typeof ConvertConvertIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/convert': typeof ConvertConvertIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_convert/convert': typeof ConvertConvertRouteWithChildren
  '/_convert/convert/': typeof ConvertConvertIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/convert' | '/convert/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/convert'
  id: '__root__' | '/' | '/_convert/convert' | '/_convert/convert/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConvertConvertRoute: typeof ConvertConvertRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_convert/convert': {
      id: '/_convert/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof ConvertConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_convert/convert/': {
      id: '/_convert/convert/'
      path: '/'
      fullPath: '/convert/'
      preLoaderRoute: typeof ConvertConvertIndexRouteImport
      parentRoute: typeof ConvertConvertRoute
    }
  }
}

interface ConvertConvertRouteChildren {
  ConvertConvertIndexRoute: typeof ConvertConvertIndexRoute
}

const ConvertConvertRouteChildren: ConvertConvertRouteChildren = {
  ConvertConvertIndexRoute: ConvertConvertIndexRoute,
}

const ConvertConvertRouteWithChildren = ConvertConvertRoute._addFileChildren(
  ConvertConvertRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConvertConvertRoute: ConvertConvertRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
