/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsPageRouteImport } from './routes/docs/$page'
import { Route as HistoryHistoryRouteImport } from './routes/_history/history'
import { Route as HistoryHistoryIndexRouteImport } from './routes/_history/history.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPageRoute = DocsPageRouteImport.update({
  id: '/docs/$page',
  path: '/docs/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryHistoryRoute = HistoryHistoryRouteImport.update({
  id: '/_history/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryHistoryIndexRoute = HistoryHistoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HistoryHistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryHistoryRouteWithChildren
  '/docs/$page': typeof DocsPageRoute
  '/docs': typeof DocsIndexRoute
  '/history/': typeof HistoryHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/$page': typeof DocsPageRoute
  '/docs': typeof DocsIndexRoute
  '/history': typeof HistoryHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_history/history': typeof HistoryHistoryRouteWithChildren
  '/docs/$page': typeof DocsPageRoute
  '/docs/': typeof DocsIndexRoute
  '/_history/history/': typeof HistoryHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/history' | '/docs/$page' | '/docs' | '/history/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs/$page' | '/docs' | '/history'
  id:
    | '__root__'
    | '/'
    | '/_history/history'
    | '/docs/$page'
    | '/docs/'
    | '/_history/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryHistoryRoute: typeof HistoryHistoryRouteWithChildren
  DocsPageRoute: typeof DocsPageRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$page': {
      id: '/docs/$page'
      path: '/docs/$page'
      fullPath: '/docs/$page'
      preLoaderRoute: typeof DocsPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_history/history': {
      id: '/_history/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_history/history/': {
      id: '/_history/history/'
      path: '/'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryHistoryIndexRouteImport
      parentRoute: typeof HistoryHistoryRoute
    }
  }
}

interface HistoryHistoryRouteChildren {
  HistoryHistoryIndexRoute: typeof HistoryHistoryIndexRoute
}

const HistoryHistoryRouteChildren: HistoryHistoryRouteChildren = {
  HistoryHistoryIndexRoute: HistoryHistoryIndexRoute,
}

const HistoryHistoryRouteWithChildren = HistoryHistoryRoute._addFileChildren(
  HistoryHistoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryHistoryRoute: HistoryHistoryRouteWithChildren,
  DocsPageRoute: DocsPageRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
